metadata:
  serviceName:  api

inputs:
  pipeline:
    configuration:
      integrations:
        - deepikaArt
        - mySlack
      environmentVariables:
        foo: bar
        test: env
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10

  sourceRepository:
    path: deepikasl/jfrog_pipelines
    gitProvider: deepikaGithub
    branches:
      include: master

  integrations:
    artifactory: deepikaArt
    sonar: deepikaSonar

configurations:

  sourceDirectory: ''

  steps:
    build:
      runtime:
        versions:
          - "16.10.0"
      onStart:
        - echo "onStart"
      onExecute:
        - echo "onExecute"
        - echo "lalala"
        - |
          if [ -z "$PIPELINES_CHART_VERSION" ]; then
          export PIPELINES_CHART_VERSION="101.44.0-m000"
          fi
      onFailure:
        - echo "onFailure"
      onSuccess:
        - echo "onSuccess"

    codeQuality:
      runtime:
        versions:
          - "16.10.0"
      onStart:
        - echo "onStart"
      onExecute:
        - echo "onExecute"
      onFailure:
        - echo "onFailure"
      onSuccess:
        - echo "onSuccess"


    sonarScan:
      runtime:
        custom:
          registry: deepikaArt
          name: stg-repo.jfrog.info/pipelines-docker/pipelines-u16go
          tag: 0.9.1
      onStart:
        - echo "onStart"
      onExecute:
        - echo "onExecute"
      onFailure:
        - echo "onFailure"
      onSuccess:
        - echo "onSuccess"

    publish:
      runtime:
        versions:
          - "16.10.0"
      onExecute:
        - echo "onExecute"
      onFailure:
        - echo "onFailure"
      onSuccess:
        - echo "onSuccess"


    clamScan:
      runtime:
        custom:
          registry: deepikaArt
          name: stg-repo.jfrog.info/pipelines-docker/pipelines-u16go
          tag: 0.9.1
      onStart:
        - echo "onStart"
      onExecute:
        - echo "onExecute"
      onFailure:
        - echo "onFailure"
      onSuccess:
        - echo "onSuccess"
        
controls:

  build:
    runtime: auto

  codeQuality:
    enabled: true
    runtime: auto

  sonarScan:
    runtime: custom

  clamScan:
    runtime: custom

  publish:
    enabled: true
    runtime: auto

  triggerBy:
    sourceRepository: true
