resources:
  - name: myArtifact
    type: Artifact
    configuration:
      sourceArtifactory: art
      repositories:
        include: jfrog*
      buildOn:
        deployed: true
        cached: true

pipelines:
  - name: my_pipe
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myArtifact
        execution:
          onExecute:
            - echo "u r here"
            
