resources:
  - name: myRepo_11
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master

  - name: artifact_test
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - example-repo
        - test1
      artifactPath:
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:
        deployed: true
      branches:
        include: artifact2
        exclude: master
  - name: artifact_2
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - example-repo-local
      artifactPath:
        include:
          - tools/*
        exclude:
          - tools/exclude/*
      buildOn:
        deployed: true
        cached: true
        deleted: true
      branches:
        include: artifactResource
  - name: artifact_deepika
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - example-repo-local
        - pipe-deepika-artifact-sample
      artifactPath:
        include:
          - default/*
          - tools/*
      buildOn:
        deployed: true
      branches:
        include: artifactResource
  - name: artifact_deepika_1
    type: Artifact
    configuration:
      jfrogPlatformProvider: deepika_jfrog
      repositories:
        - pipe-deepika-artifact-sample
      artifactPath:
        include:
          - tools/*
      buildOn:
        deployed: true
      branches:
        include: artifact2

pipelines:
  - name: my_pipe_1
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifact_deepika_1
            - name: myRepo_11
        execution:
          onExecute:
            - echo "executing step_1"
  - name: my_pipe_2
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: artifact_2
        execution:
          onExecute:
            - echo "executing step_1"
            
