resources:
  - name: myRepo
    type: GITRepo
    configuration:
      path: deepikasl/jfrog_pipelines
      gitProvider: deepikaGithub
      branches:
        include: master
  - name: submodule
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: submodule

  - name: propertyBag
    type: PropertyBag
    configuration:
      foo: bar
      foo1: bar1
      foo2: bar2

pipelines:
  - name: demo_manual_main
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: manual_trigger
        type: Bash
        configuration:
          inputResources:
            - name: myRepo
          outputResources:
            - name: propertyBag
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - write_output propertyBag "foo=$run_number"
      - name: submodule_test
        type: Bash
        configuration:
          inputResources:
            - name: submodule
          inputSteps:
            - name: manual_trigger
        execution:
          onExecute:
            - pushd $res_submodule_resourcePath
            - ls
            - pushd myFirstSubModule
            - ls
            
