resources:
  - name: git_res_1
    type: GITRepo
    configuration:
      path: deepikasl/multi-source-folder
      gitProvider: deepikaGithub
      branches:
        include: autoSyncTest
      pullRequestSourceBranches:
        include: autoSyncTest
      buildOn:
        pullRequestCreate: false
        commit: true

pipelines:
  - name: demo_manual_main
    configuration:
      integrations:
        - name: deepikaGithub
    steps:
      - name: first_step
        type: Bash
        configuration:
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: second_step
        type: Bash
        configuration:
          inputSteps:
            - name: first_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: third_step
        type: Bash
        configuration:
          inputSteps:
            - name: second_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: forth_step
        type: Bash
        configuration:
          inputSteps:
            - name: third_step
        execution:
          onExecute:
            - printenv
      - name: fifth_step
        type: Bash
        configuration:
          inputSteps:
            - name: forth_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: sixth_step
        type: Bash
        configuration:
          inputSteps:
            - name: fifth_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: seventh_step
        type: Bash
        configuration:
          inputSteps:
            - name: sixth_step
        execution:
          onExecute:
            - printenv
      - name: eighth_step
        type: Bash
        configuration:
          inputSteps:
            - name: seventh_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv
      - name: ninth_step
        type: Bash
        configuration:
          inputSteps:
            - name: eighth_step
          inputResources:
            - name: git_res_1
        execution:
          onExecute:
            - printenv

