resources:
  - name: nodeRepo
    type: GitRepo
    configuration:
      path: deepikasl/sample_node
      gitProvider: deepikaGithub
      branches:
        include: master

pipelines:
  - name: sample_node_app
    steps:
      - name: node_setup
        type: Bash
        configuration:
          affinityGroup: node_app
          integrations:
            - name: deepika_art_entplus
          inputResources:
            - name: nodeRepo
        execution:
          onStart:
            - npm config set registry "https://entplus.jfrog.io/artifactory/api/npm/npm-virtual"
            - curl -u"${int_deepika_art_entplus_user}":"${int_deepika_art_entplus_apikey}" "https://entplus.jfrog.io/api/npm/auth" >> ~/.npmrc
          onExecute:
            - pushd $res_nodeRepo_resourcePath 
            - npm install
            - mkdir -p $shared_workspace/repo/node_modules
            - mv ./node_modules $shared_workspace/repo/node_modules
            - popd
            
      - name: app_build
        type: Bash
        configuration:
          affinityGroup: node_app
          inputResources:
            - name: nodeRepo
          inputSteps:
            - name: node_setup
          integrations:
            - name: deepika_art
        execution:
          onStart:
            - pushd $res_nodeRepo_resourcePath
            - mv $shared_workspace/repo/node_modules .
          onExecute:
            - npm run build
            - jfrog rt upload dist/index.js example-repo-local/node_app.js
            - popd
          
        
          
