valuesFilePath: ./values.yml

pipelines:
{{ range $service, $environments := .Values.services }}
{{ range $environment := $environments }}
{{ range $_, $action := $.Values.actions }}
  - name: {{ $service | replace "-" "_" }}_{{ $environment }}_{{ $action }}
    configuration:
      retentionPolicy:
         maxAgeDays: 1
         minRuns: 1
    steps:
      - name: submodule_test
        type: Bash
        configuration:
          integrations:
            - name: deepikaGithub
        execution:
          onExecute:
            - printenv 
{{ end }}
{{ end }}
{{ end }}
